name: HopperLagDetector
api-version: 1.13
version: @version@
main: net.azisaba.hopperlagdetector.HopperLagDetector
commands:
  hopperlagdetector:
    permission: hopperlagdetector.command
    aliases: [hld]
